#!/usr/bin/env bash
# Displays the number of occurrences of each IP and HTTP code in apache-access.log

awk '{count[$1" "$9]++}
     END {
         for (key in count)
             if (key != "") print count[key], key
     }' apache-access.log | sort -nr
