#!/usr/bin/env bash
# Displays the number of occurrences of each IP and HTTP code in apache-access.log
cat apache-access.log | awk '{count[$1" "$9]++} END {for (i in count) print count[i], i}' | sort -rn 
