#!/usr/bin/env bash
# This script checks the status of the file named "school"

if [ -e school ]; then
    if [ -f school ]; then
        if [ -s school ]; then
            echo "File exist and is a regular file"
        else
            echo "school exists but empty"
        fi
    else
        echo "school exists but it’s a directory"
    fi
else
    echo "school doesn’t exist"
fi
