#!/usr/bin/env bash
#salam
if [ -e school ]; then
    if [ -s school ]; then
        if [ -f school ]; then
            echo "File exist and is a regular file"
        else
            echo "school file is not a regular file"
        fi

    else
        echo "school exists but it’s a directory"
    fi


else
    echo "school file does not exist"
fi


