#!/usr/bin/env bash
#salam
if [ -e school ]; then
    echo "school file exists"
    if [ -s school ]; then
        echo "school file is empty"
    else
        echo " school exists but empty"
    fi
    if [ -f school ]; then
        echo "File exist and is a regular file"
    else
        echo "school file is not a regular file"
    fi

else    
    echo "school file does not exist"
fi


