#!/usr/bin/env bash
#salam
for pid in /proc/[0-9]*; do
    if [ -f "$pid/comm" ]; then
        name=$(cat "$pid/comm")
        if echo "$name" | grep -qi "bash"; then
            echo "$(basename "$pid") - $name"
        fi
    fi
done
